//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DotAReplay.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DOTAREPLAY_DIALOG           102
#define IDD_GAMEINFO                    129
#define IDD_GAMEINFO1                   130
#define IDD_PLAYERINFO                  130
#define IDD_SETTINGSPAGE                131
#define IDD_BATCHCOPY                   132
#define IDR_MAINFRAME                   133
#define IDD_GAMEINFO2                   133
#define IDD_TIMELINE                    133
#define IDR_TRAYI                       133
#define IDB_REPLAYS                     134
#define IDD_PLAYERACTIONS               134
#define IDI_PLAY                        135
#define IDD_PRESENT                     135
#define IDR_TRAYICON                    136
#define IDC_ELFHAND                     137
#define IDI_TRAYICON                    139
#define IDD_UPDATE                      140
#define IDD_PLAYERGOLD                  141
#define IDD_SEARCHOPTS                  142
#define IDD_PLAYERSTATS                 143
#define IDD_SCREENSHOT                  144
#define IDD_SCREENSHOT1                 145
#define IDD_HEROCHART                   145
#define IDD_PLAYEREXP                   146
#define IDD_WORKSHOP                    147
#define IDD_PROGRESS                    149
#define IDD_GETDATA                     150
#define IDD_CHATFILTERS                 151
#define IDD_DRAFT                       152
#define IDD_ACTIONLOG                   153
#define IDD_SCRIPTEDITOR                154
#define IDR_SCRIPT                      155
#define IDD_PRESENT2                    155
#define IDC_ZOOMIN                      156
#define IDD_TAGEDITOR                   157
#define IDC_EDIT1                       1000
#define IDC_REPLAYFILE                  1000
#define IDC_SELPLAYER                   1000
#define IDC_REPLAYPATH                  1000
#define IDC_CURTIME                     1000
#define IDC_RESULT                      1000
#define IDC_BUFFER                      1000
#define IDC_MTEXT                       1000
#define IDC_VERSION                     1000
#define IDC_SCRIPTBOX                   1000
#define IDC_PARSEREPLAY                 1001
#define IDC_MAXFILES                    1001
#define IDC_VERSIONA                    1001
#define IDC_COPYVER                     1001
#define IDC_OUTPUT                      1001
#define IDC_EDIT2                       1002
#define IDC_CHAT                        1002
#define IDC_BROWSEREPLAY                1002
#define IDC_COPYFORMAT                  1002
#define IDC_COMMENT                     1002
#define IDC_AFKTIME                     1002
#define IDC_PNAME1                      1002
#define IDC_NOTES                       1002
#define IDC_PLAYERNAME                  1002
#define IDC_RICHEDIT21                  1003
#define IDC_CHATBOX                     1003
#define IDC_CHATLIFE                    1003
#define IDC_PNAME2                      1003
#define IDC_GAMEMODE                    1003
#define IDC_CHECK1                      1004
#define IDC_AUTOCOPY                    1004
#define IDC_PLAY                        1004
#define IDC_REFRESH                     1004
#define IDC_INFO_DATE                   1004
#define IDC_PNAME3                      1004
#define IDC_OBSMSG                      1004
#define IDC_ALL_CHAT                    1004
#define IDC_RAWCODES                    1004
#define IDC_TAB1                        1005
#define IDC_TABS                        1005
#define IDC_AUTOVIEW                    1005
#define IDC_INFO_PATCH                  1005
#define IDC_PNAME4                      1005
#define IDC_MODIFY                      1005
#define IDC_OBSPING                     1005
#define IDC_ALLY_CHAT                   1005
#define IDC_MAININFO                    1006
#define IDC_TIMEDEATH                   1006
#define IDC_INFO_MAP                    1006
#define IDC_PNAME5                      1006
#define IDC_ALLPING                     1006
#define IDC_OBSERVER_CHAT               1006
#define IDC_BACK                        1006
#define IDC_LIST1                       1007
#define IDC_PLAYERINFO                  1007
#define IDC_FILELIST                    1007
#define IDC_ACTIONCHART                 1007
#define IDC_VIEWWINDOW                  1007
#define IDC_INFO_NAME                   1007
#define IDC_VERSIONB                    1007
#define IDC_ALLMSG                      1007
#define IDC_PRIVATE_CHAT                1007
#define IDC_TAGLIST                     1007
#define IDC_ITEMLIST                    1008
#define IDC_REPDELAY                    1008
#define IDC_INFO_HOST                   1008
#define IDC_LENGTHA                     1008
#define IDC_GAME_COMMANDS               1008
#define IDC_PARSEREPLAY3                1008
#define IDC_FORWARD                     1008
#define IDC_SKILLLIST                   1009
#define IDC_INFO_SAVER                  1009
#define IDC_WARDLIFE                    1009
#define IDC_LEAVING_PLAYERS             1009
#define IDC_COMBO1                      1010
#define IDC_PRESET                      1010
#define IDC_PMODE1                      1010
#define IDC_REPDELAYITEM                1010
#define IDC_FOUNDLIST                   1010
#define IDC_GAME_PAUSES                 1010
#define IDC_SEARCHTYPE                  1010
#define IDC_INFO_LENGTH                 1011
#define IDC_IMGURL                      1011
#define IDC_PMODE2                      1011
#define IDC_CONTROL_SHARING             1011
#define IDC_SEARCHPLAYER                1011
#define IDC_INFO_PLAYERS                1012
#define IDC_PMODE3                      1012
#define IDC_YOURNAME                    1012
#define IDC_HERO_KILLS                  1012
#define IDC_FILETREE                    1013
#define IDC_INFO_SCORE                  1013
#define IDC_PMODE4                      1013
#define IDC_WARPATH                     1013
#define IDC_TOWER_KILLS                 1013
#define IDC_FINDFOLDER                  1014
#define IDC_INFO_WINNER                 1014
#define IDC_PMODE5                      1014
#define IDC_RAX_KILLS                   1014
#define IDC_HELPFORMAT                  1015
#define IDC_BATCH                       1015
#define IDC_INFO_OBSERVERS              1015
#define IDC_MFUNC                       1015
#define IDC_COURIER_KILLS               1015
#define IDC_BATCHCOPY                   1016
#define IDC_ABOUT                       1016
#define IDC_GEN_MODE                    1016
#define IDC_NTEXT                       1016
#define IDC_TREE_HEALTH                 1016
#define IDC_BATCHHELP                   1017
#define IDC_FROMFILE                    1017
#define IDC_USE_ICONS                   1017
#define IDC_UPDATEPATH                  1017
#define IDC_NFUNC                       1017
#define IDC_ROSHAN                      1017
#define IDC_TOFILE                      1018
#define IDC_EXPLORE                     1018
#define IDC_PLAYERLIST                  1018
#define IDC_RESETPATH                   1018
#define IDC_FTEXT                       1018
#define IDC_CHAT_MESSAGES               1018
#define IDC_BATCHPROGRESS               1019
#define IDC_PLAYER_COLOR                1019
#define IDC_ABOUT2                      1019
#define IDC_README                      1019
#define IDC_FFUNC                       1019
#define IDC_SEARCH                      1019
#define IDC_GAME_MESSAGES               1019
#define IDC_ETCHED                      1020
#define IDC_PLAYER_LEVEL                1020
#define IDC_UPDATES                     1020
#define IDC_COUNTA                      1020
#define IDC_GAME_COMMANDS2              1020
#define IDC_AEGIS                       1020
#define IDC_WATCHREPLAY                 1021
#define IDC_PLAYER_HEROES               1021
#define IDC_COUNTB                      1021
#define IDC_RESETWAR                    1021
#define IDC_PLAYER_CREEPS               1022
#define IDC_PATCHA                      1022
#define IDC_NOTIFY_RUNE                 1022
#define IDC_TIMESLIDER                  1023
#define IDC_PLAYER_GOLD                 1023
#define IDC_PATCHB                      1023
#define IDC_RESETPATH2                  1023
#define IDC_BROWSEPATH                  1023
#define IDC_GAME_MODE                   1023
#define IDC_PLAYER_LANE                 1024
#define IDC_BROWSEWAR                   1024
#define IDC_PICKS_BANS                  1024
#define IDC_PICFRAME                    1025
#define IDC_PLAYER_APM                  1025
#define IDC_FASTKILLS                   1025
#define IDC_SPIN1                       1026
#define IDC_PLAYER_LEFT                 1026
#define IDC_SPREES                      1026
#define IDC_SPEED                       1027
#define IDC_PLAYER_GROUP                1027
#define IDC_ACTIONGRAPH                 1028
#define IDC_DETAIL_SKILL                1028
#define IDC_GRAPHAREA                   1029
#define IDC_DETAIL_SKTIME               1029
#define IDC_TIMEPIC                     1030
#define IDC_GROUPS                      1030
#define IDC_DETAIL_ITEM                 1030
#define IDC_DRAWCHAT                    1031
#define IDC_DETAIL_ITTIME               1031
#define IDC_USETRAY                     1032
#define IDC_SAVEPR                      1032
#define IDC_DETAIL_ITCOST               1033
#define IDC_DRAWWARDS                   1033
#define IDC_NEWPR                       1033
#define IDC_DETAIL_P1                   1034
#define IDC_DRAWPINGS                   1034
#define IDC_DETAIL_P2                   1035
#define IDC_AUTOUPDATE                  1035
#define IDC_DETAIL_P3                   1036
#define IDC_SHOWLEVELS                  1036
#define IDC_DETAIL_P4                   1037
#define IDC_SHOWASSEMBLE                1037
#define IDC_DETAIL_P5                   1038
#define IDC_SKILLCOLORS                 1038
#define IDC_TIP_P1                      1039
#define IDC_SHOWASSEMBLE2               1039
#define IDC_SYNCSEL                     1039
#define IDC_INFO_NAME2                  1039
#define IDC_INFO_MODE                   1039
#define IDC_DETAIL_S1                   1039
#define IDC_TIP_P2                      1040
#define IDC_USELOG                      1040
#define IDC_DETAIL_S2                   1040
#define IDC_USE_ICONS2                  1040
#define IDC_FORUM_ICONS                 1040
#define IDC_TIP_P3                      1041
#define IDC_AUTOUPDATE2                 1041
#define IDC_ENABLEURL                   1041
#define IDC_FUNCTION                    1041
#define IDC_TIP_P4                      1042
#define IDC_SMOOTHGOLD                  1042
#define IDC_TIP_P5                      1043
#define IDC_IGNOREBASIC                 1043
#define IDC_DETAIL_P6                   1044
#define IDC_DRAWBUILDINGS               1044
#define IDC_TIP_P6                      1045
#define IDC_DETAIL_P7                   1046
#define IDC_TIP_P7                      1047
#define IDC_DETAIL_P8                   1048
#define IDC_TIP_P8                      1049
#define IDC_DETAIL_P9                   1050
#define IDC_TIP_P9                      1051
#define IDC_DETAIL_P10                  1052
#define IDC_TIP_P10                     1053
#define IDC_DETAIL_ACTION               1054
#define IDC_DETAIL_GROUPS               1055
#define IDC_UPDATE                      1056
#define IDC_COPY                        1057
#define IDC_FORUM                       1057
#define IDC_PREVIEW                     1058
#define IDC_FORUM2                      1058
#define IDC_PLAYER_ITEMS                1059
#define IDC_DELPR                       1060
#define IDC_STRIPTAGS                   1061
#define IDC_SETREGOPEN                  1062
#define IDC_OPTTABS                     1063
#define IDC_REPLAYPATH_TIP              1064
#define IDC_MAXFILES_TIP                1065
#define IDC_COPYFORMAT_TIP              1066
#define IDC_REPDELAY_TIP                1067
#define IDC_TIMELINE_BOX                1068
#define IDC_WARDLIFE_TIP                1069
#define IDC_CHATLIFE_TIP                1070
#define IDC_TIMEDEATH_TIP               1071
#define IDC_IMGURL_TIP                  1072
#define IDC_IMGRECT                     1073
#define IDC_REPDELAY_TIP2               1073
#define IDC_YOURNAME_TIP                1073
#define IDC_REPDELAYITEM_TIP            1074
#define IDC_ALLSENT                     1075
#define IDC_WARPATH_TIP                 1075
#define IDC_NOSENT                      1076
#define IDC_SHOWDETAILS                 1076
#define IDC_ALLSCOURGE                  1077
#define IDC_DET_SAVED                   1077
#define IDC_NOSCOURGE                   1078
#define IDC_DET_SIZE                    1078
#define IDC_DET_NAME                    1079
#define IDC_DET_SAVER                   1080
#define IDC_DET_RATIO                   1081
#define IDC_DET_LENGTH                  1082
#define IDC_DET_WARN                    1083
#define IDC_DET_BOX                     1084
#define IDC_SHOWDETAILS2                1085
#define IDC_SAVECACHE                   1085
#define IDC_DET_LENGTH2                 1086
#define IDC_DET_MODE                    1086
#define IDC_PHERO1                      1086
#define IDC_SAVEDA                      1087
#define IDC_SAVEDB                      1088
#define IDC_PHERO2                      1089
#define IDC_PHERO3                      1090
#define IDC_STATS                       1090
#define IDC_PHERO4                      1091
#define IDC_CACHEALL                    1091
#define IDC_PHERO5                      1092
#define IDC_RESET                       1092
#define IDC_WARDS                       1092
#define IDC_FINALBUILD                  1093
#define IDC_RESET2                      1093
#define IDC_FORUMICONS                  1093
#define IDC_SAVEDB2                     1094
#define IDC_LENGTHB                     1094
#define IDC_PLAYERS                     1094
#define IDC_NAME                        1095
#define IDC_BYDATE                      1096
#define IDC_PLAYERSTATS                 1097
#define IDC_HEROLIST                    1098
#define IDC_WORKSHOP                    1098
#define IDC_TAVERNAREA                  1099
#define IDC_COPY_MATCHUP                1099
#define IDC_BUTTON1                     1100
#define IDC_MAPBROWSE                   1100
#define IDC_FILTERS                     1100
#define IDC_LOADACTIONS                 1100
#define IDC_WEBSITE                     1101
#define IDC_FINDNEXT                    1101
#define IDC_SEP1                        1102
#define IDC_SEP2                        1103
#define IDC_SEP3                        1104
#define IDC_CHATFONT                    1104
#define IDC_SEP4                        1105
#define IDC_SEP5                        1106
#define IDC_SEP6                        1107
#define IDC_SKILLTIP                    1108
#define IDC_ITEMTIP                     1109
#define IDC_FOLDERLOAD                  1110
#define IDC_MAPIMG                      1111
#define IDC_LIST2                       1112
#define IDC_CHATLIST                    1112
#define IDC_CHATCLRTIP                  1113
#define IDC_CHATCLRBOX                  1114
#define IDC_CHATPLCLRTIP                1115
#define IDC_CHATPLCLR                   1117
#define IDC_PRGTEXT                     1118
#define IDC_CLOSEST                     1119
#define IDC_VERSION_TIP                 1120
#define IDC_COPYVERSION                 1121
#define IDC_LOADMAP                     1122
#define IDC_LOADTHISMAP                 1123
#define IDC_MAPTOLOAD                   1124
#define IDC_SAVEDATA                    1125
#define IDC_SAVECHOICE                  1126
#define IDC_TIP                         1127
#define IDC_CHATHEROES                  1129
#define IDC_SEARCHFOR                   1130
#define IDC_RELTIME                     1130
#define IDC_DRAFTPOOL                   1131
#define IDC_CHATASSISTS                 1131
#define IDC_DRAFT_BANS                  1132
#define IDC_CHATASSISTS2                1132
#define IDC_SHOWEMPTY                   1132
#define IDC_DRAFT_PICKS                 1133
#define IDC_SENTINEL_TIP                1134
#define IDC_SCOURGE_TIP                 1135
#define IDC_BANS_TIP                    1136
#define IDC_PICKS_TIP                   1137
#define IDC_ACTIONS                     1138
#define IDC_FUNCTION_TIP                1140
#define IDC_SCRIPTTREE                  1141
#define IDC_SCRIPTFRAME                 1143
#define IDC_NOBUILD                     1144
#define IDC_FINDPREV                    1145
#define IDC_KDD0                        1146
#define IDC_SEPARATOR                   1147
#define IDC_KDD1                        1151
#define IDC_KDD2                        1152
#define IDC_KDD3                        1153
#define IDC_KDD4                        1154
#define IDC_KILLDET                     1155
#define ID_SCRIPT_SAVE                  32771
#define ID_SCRIPT_EXPORT                32772
#define ID_SCRIPT_IMPORT                32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1148
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
